#!/usr/bin/env node

const { lexer } = require('./lexer.js');
const { parser } = require('./parse.js');
const { evalAst } = require('./eval.js');

let code = `
# simple math
(console.log (* (+ 2) (+ 1 7)))

# js interop
(console.log "hello world") #after comment

(Math.max 100 123 77)
`;

if (process.argv.length > 2) {
  const uargs = process.argv.slice(2);
  if (uargs[0] === '-e' || uargs[0] === '--eval')
    code = uargs[1];
  else
    code = require('fs').readFileSync(uargs[0], 'utf8');
}

const tokens = lexer(code);
console.log(tokens);

const ast = parser(tokens);
console.log(ast);

const ret = evalAst(ast);
console.log(ret);

